name: transit_go_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.3.0
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  lottie: ^3.3.1
  mobile_scanner: ^6.0.7
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  intl: ^0.20.2
  google_maps_flutter: ^2.12.0
  flutter_dotenv: ^5.2.1
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/
    - assets/lottie/
    - .env


